project_id = "wqfefrlnzfkngkihlyij"

[functions.get-all-shipments-admin]
verify_jwt = false

[functions.shopify-compliance-webhooks]
verify_jwt = false

[functions.easyship-webhook]
verify_jwt = false